
/**
 * THIS FILE IS AUTOGENERATED BY `yarn generate`
 *
 * DO NOT EDIT MANUALLY
 */
    
declare module '*LoginUser.graphql' {
  import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
  import { LoginUserMutation, LoginUserMutationVariables } from 'graphql-gen/types';
  const LoginUserDocument: DocumentNode<
    LoginUserMutation,
    LoginUserMutationVariables
  >;
  export default LoginUserDocument;
}