
/**
 * THIS FILE IS AUTOGENERATED BY `yarn generate`
 *
 * DO NOT EDIT MANUALLY
 */
    
declare module '*CreateTask.graphql' {
  import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
  import { CreateTaskMutation, CreateTaskMutationVariables } from 'graphql-gen/types';
  const CreateTaskDocument: DocumentNode<
    CreateTaskMutation,
    CreateTaskMutationVariables
  >;
  export default CreateTaskDocument;
}

declare module '*DeleteTask.graphql' {
  import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
  import { DeleteTaskMutation, DeleteTaskMutationVariables } from 'graphql-gen/types';
  const DeleteTaskDocument: DocumentNode<
    DeleteTaskMutation,
    DeleteTaskMutationVariables
  >;
  export default DeleteTaskDocument;
}

declare module '*UpdateTask.graphql' {
  import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
  import { UpdateTaskMutation, UpdateTaskMutationVariables } from 'graphql-gen/types';
  const UpdateTaskDocument: DocumentNode<
    UpdateTaskMutation,
    UpdateTaskMutationVariables
  >;
  export default UpdateTaskDocument;
}

declare module '*GetDashboard.graphql' {
  import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
  import { GetDashboardQuery, GetDashboardQueryVariables } from 'graphql-gen/types';
  const GetDashboardDocument: DocumentNode<
    GetDashboardQuery,
    GetDashboardQueryVariables
  >;
  export default GetDashboardDocument;
}

declare module '*GetTasks.graphql' {
  import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
  import { GetTasksQuery, GetTasksQueryVariables } from 'graphql-gen/types';
  const GetTasksDocument: DocumentNode<
    GetTasksQuery,
    GetTasksQueryVariables
  >;
  export default GetTasksDocument;
}

declare module '*LoginUser.graphql' {
  import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
  import { LoginUserMutation, LoginUserMutationVariables } from 'graphql-gen/types';
  const LoginUserDocument: DocumentNode<
    LoginUserMutation,
    LoginUserMutationVariables
  >;
  export default LoginUserDocument;
}